// Auto-generated by `supabase gen types typescript` / Supabase MCP.
// Re-generate when the schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      contact_submissions: {
        Row: {
          created_at: string
          email: string
          id: string
          interest: string
          message: string
          name: string
          phone: string | null
          status: string
          user_agent: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          interest: string
          message: string
          name: string
          phone?: string | null
          status?: string
          user_agent?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          interest?: string
          message?: string
          name?: string
          phone?: string | null
          status?: string
          user_agent?: string | null
        }
        Relationships: []
      }
      listings: {
        Row: {
          address_city: string
          address_postal_code: string | null
          address_region: string
          address_street: string
          baths: number
          beds: number
          created_at: string
          description: string
          features: string[]
          hero_image: string | null
          id: string
          images: Json
          is_featured: boolean
          listed_at: string
          lot_sqft: number | null
          neighborhood: string
          price_cents: number
          slug: string
          sqft: number | null
          status: string
          title: string
          updated_at: string
          year_built: number | null
        }
        Insert: {
          address_city?: string
          address_postal_code?: string | null
          address_region?: string
          address_street: string
          baths: number
          beds: number
          created_at?: string
          description?: string
          features?: string[]
          hero_image?: string | null
          id?: string
          images?: Json
          is_featured?: boolean
          listed_at?: string
          lot_sqft?: number | null
          neighborhood: string
          price_cents: number
          slug: string
          sqft?: number | null
          status?: string
          title: string
          updated_at?: string
          year_built?: number | null
        }
        Update: {
          address_city?: string
          address_postal_code?: string | null
          address_region?: string
          address_street?: string
          baths?: number
          beds?: number
          created_at?: string
          description?: string
          features?: string[]
          hero_image?: string | null
          id?: string
          images?: Json
          is_featured?: boolean
          listed_at?: string
          lot_sqft?: number | null
          neighborhood?: string
          price_cents?: number
          slug?: string
          sqft?: number | null
          status?: string
          title?: string
          updated_at?: string
          year_built?: number | null
        }
        Relationships: []
      }
      newsletter_subscribers: {
        Row: {
          confirmed: boolean
          created_at: string
          email: string
          id: string
          source: string | null
        }
        Insert: {
          confirmed?: boolean
          created_at?: string
          email: string
          id?: string
          source?: string | null
        }
        Update: {
          confirmed?: boolean
          created_at?: string
          email?: string
          id?: string
          source?: string | null
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Update"]
